name: SkyWars
authors: [svile, Laith98Dev]
description: SkyWars plugin
main: svile\skywars\SWmain
version: 1.8.1
api: [4.0.0]
load: STARTUP
depend: [EconomyAPI]

commands:
 sw:
  description: SkyWars main command
  default: true
  permission: skywars.command

permissions:
  skywars.command:
    default: true
  skywars.command.join:
    default: true
  skywars.command.quit:
    default: true
  skywars.command.create:
    default: op
  skywars.command.setspawn:
    default: op
  skywars.command.list: 
    default: true
  skywars.command.delete:
    default: op
  skywars.command.signdelete:
    default: op
  skywars.setsign:
    default: op
  skywars.removesign:
    default: op
  
