name: SkyWars
authors: [svile, Laith98Dev]
description: SkyWars plugin
main: svile\skywars\SWmain
version: 1.8.0
api: [4.0.0]
load: STARTUP
depend: [EconomyAPI]

commands:
 sw:
  description: SkyWars main command
  permission: skywars.command

permissions:
  skywars.command:
    default: op
  skywars.command.join:
    default: true
  skywars.command.quit:
    default: true
  skywars.removesign:
    default: op
  
