name: SkyWars
authors: [svile, Laith98Dev]
description: SkyWars plugin
main: svile\skywars\SWmain
version: 1.8.1
api: [4.0.0]
load: STARTUP
depend: [EconomyAPI]

commands:
 sw:
  description: SkyWars main command
  permission: skywars.command
 swjoin:
  description: SkyWars join command
  permission: skywars.command.join
 swquit:
  description: SkyWars quit command
  permission: skywars.command.quit

permissions:
  skywars.command:
    default: op
  skywars.command.join:
    default: true
  skywars.command.quit:
    default: true
  skywars.setsign:
    default: op
  skywars.removesign:
    default: op
  
